// Code generated by "so bind"; DO NOT EDIT.

package libsodium

import "solod.dev/so/c"
var _ c.Char

//so:extern crypto_aead_aes256gcm_state
type Aead_aes256gcm_state struct {
	Opaque [512]c.UChar `c:"opaque"`
}

//so:extern crypto_hash_sha512_state
type Hash_sha512_state struct {
	State [8]uint64 `c:"state"`
	Count [2]uint64 `c:"count"`
	Buf [128]uint8 `c:"buf"`
}

//so:extern crypto_auth_hmacsha512_state
type Auth_hmacsha512_state struct {
	Ictx Hash_sha512_state `c:"ictx"`
	Octx Hash_sha512_state `c:"octx"`
}

//so:extern crypto_auth_hmacsha512256_state
type Auth_hmacsha512256_state struct {
	Ictx Hash_sha512_state `c:"ictx"`
	Octx Hash_sha512_state `c:"octx"`
}

//so:extern crypto_hash_sha256_state
type Hash_sha256_state struct {
	State [8]uint32 `c:"state"`
	Count uint64 `c:"count"`
	Buf [64]uint8 `c:"buf"`
}

//so:extern crypto_auth_hmacsha256_state
type Auth_hmacsha256_state struct {
	Ictx Hash_sha256_state `c:"ictx"`
	Octx Hash_sha256_state `c:"octx"`
}

//so:extern crypto_core_keccak1600_state
type Core_keccak1600_state struct {
	Opaque [224]c.UChar `c:"opaque"`
}

//so:extern crypto_generichash_blake2b_state
type Generichash_blake2b_state struct {
	Opaque [384]c.UChar `c:"opaque"`
}

//so:extern crypto_generichash_state
type Generichash_state struct {
	Opaque [384]c.UChar `c:"opaque"`
}

//so:extern crypto_hash_sha3256_state
type Hash_sha3256_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_hash_sha3512_state
type Hash_sha3512_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_kdf_hkdf_sha256_state
type Kdf_hkdf_sha256_state struct {
	St Auth_hmacsha256_state `c:"st"`
}

//so:extern crypto_kdf_hkdf_sha512_state
type Kdf_hkdf_sha512_state struct {
	St Auth_hmacsha512_state `c:"st"`
}

//so:extern crypto_onetimeauth_poly1305_state
type Onetimeauth_poly1305_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_onetimeauth_state
type Onetimeauth_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_secretstream_xchacha20poly1305_state
type Secretstream_xchacha20poly1305_state struct {
	K [32]c.UChar `c:"k"`
	Nonce [12]c.UChar `c:"nonce"`
	_pad [8]c.UChar
}

//so:extern crypto_sign_ed25519ph_state
type Sign_ed25519ph_state struct {
	Hs Hash_sha512_state `c:"hs"`
}

//so:extern crypto_sign_state
type Sign_state struct {
	Hs Hash_sha512_state `c:"hs"`
}

//so:extern crypto_xof_shake128_state
type Xof_shake128_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_xof_shake256_state
type Xof_shake256_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_xof_turboshake128_state
type Xof_turboshake128_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern crypto_xof_turboshake256_state
type Xof_turboshake256_state struct {
	Opaque [256]c.UChar `c:"opaque"`
}

//so:extern randombytes_implementation
type Randombytes_implementation struct {
	Implementation_name func() *c.Char `c:"implementation_name"`
	Random func() uint32 `c:"random"`
	Stir func() `c:"stir"`
	Uniform func(uint32) uint32 `c:"uniform"`
	Buf func(any, c.Size) `c:"buf"`
	Close func() c.Int `c:"close"`
}

//so:extern SODIUM_LIBRARY_VERSION_MAJOR
const LIBRARY_VERSION_MAJOR = 26

//so:extern SODIUM_LIBRARY_VERSION_MINOR
const LIBRARY_VERSION_MINOR = 4

//so:extern crypto_aead_aegis128l_ABYTES
const Aead_aegis128l_ABYTES = 32

//so:extern crypto_aead_aegis128l_KEYBYTES
const Aead_aegis128l_KEYBYTES = 16

//so:extern crypto_aead_aegis128l_NPUBBYTES
const Aead_aegis128l_NPUBBYTES = 16

//so:extern crypto_aead_aegis128l_NSECBYTES
const Aead_aegis128l_NSECBYTES = 0

//so:extern crypto_aead_aegis256_ABYTES
const Aead_aegis256_ABYTES = 32

//so:extern crypto_aead_aegis256_KEYBYTES
const Aead_aegis256_KEYBYTES = 32

//so:extern crypto_aead_aegis256_NPUBBYTES
const Aead_aegis256_NPUBBYTES = 32

//so:extern crypto_aead_aegis256_NSECBYTES
const Aead_aegis256_NSECBYTES = 0

//so:extern crypto_aead_aes256gcm_ABYTES
const Aead_aes256gcm_ABYTES = 16

//so:extern crypto_aead_aes256gcm_KEYBYTES
const Aead_aes256gcm_KEYBYTES = 32

//so:extern crypto_aead_aes256gcm_NPUBBYTES
const Aead_aes256gcm_NPUBBYTES = 12

//so:extern crypto_aead_aes256gcm_NSECBYTES
const Aead_aes256gcm_NSECBYTES = 0

//so:extern crypto_aead_chacha20poly1305_ABYTES
const Aead_chacha20poly1305_ABYTES = 16

//so:extern crypto_aead_chacha20poly1305_KEYBYTES
const Aead_chacha20poly1305_KEYBYTES = 32

//so:extern crypto_aead_chacha20poly1305_NPUBBYTES
const Aead_chacha20poly1305_NPUBBYTES = 8

//so:extern crypto_aead_chacha20poly1305_NSECBYTES
const Aead_chacha20poly1305_NSECBYTES = 0

//so:extern crypto_aead_chacha20poly1305_ietf_ABYTES
const Aead_chacha20poly1305_ietf_ABYTES = 16

//so:extern crypto_aead_chacha20poly1305_ietf_KEYBYTES
const Aead_chacha20poly1305_ietf_KEYBYTES = 32

//so:extern crypto_aead_chacha20poly1305_ietf_NPUBBYTES
const Aead_chacha20poly1305_ietf_NPUBBYTES = 12

//so:extern crypto_aead_chacha20poly1305_ietf_NSECBYTES
const Aead_chacha20poly1305_ietf_NSECBYTES = 0

//so:extern crypto_aead_xchacha20poly1305_ietf_ABYTES
const Aead_xchacha20poly1305_ietf_ABYTES = 16

//so:extern crypto_aead_xchacha20poly1305_ietf_KEYBYTES
const Aead_xchacha20poly1305_ietf_KEYBYTES = 32

//so:extern crypto_aead_xchacha20poly1305_ietf_NPUBBYTES
const Aead_xchacha20poly1305_ietf_NPUBBYTES = 24

//so:extern crypto_aead_xchacha20poly1305_ietf_NSECBYTES
const Aead_xchacha20poly1305_ietf_NSECBYTES = 0

//so:extern crypto_auth_BYTES
const Auth_BYTES = 32

//so:extern crypto_auth_KEYBYTES
const Auth_KEYBYTES = 32

//so:extern crypto_auth_hmacsha256_BYTES
const Auth_hmacsha256_BYTES = 32

//so:extern crypto_auth_hmacsha256_KEYBYTES
const Auth_hmacsha256_KEYBYTES = 32

//so:extern crypto_auth_hmacsha512256_BYTES
const Auth_hmacsha512256_BYTES = 32

//so:extern crypto_auth_hmacsha512256_KEYBYTES
const Auth_hmacsha512256_KEYBYTES = 32

//so:extern crypto_auth_hmacsha512_BYTES
const Auth_hmacsha512_BYTES = 64

//so:extern crypto_auth_hmacsha512_KEYBYTES
const Auth_hmacsha512_KEYBYTES = 32

//so:extern crypto_box_BEFORENMBYTES
const Box_BEFORENMBYTES = 32

//so:extern crypto_box_BOXZEROBYTES
const Box_BOXZEROBYTES = 16

//so:extern crypto_box_MACBYTES
const Box_MACBYTES = 16

//so:extern crypto_box_NONCEBYTES
const Box_NONCEBYTES = 24

//so:extern crypto_box_PUBLICKEYBYTES
const Box_PUBLICKEYBYTES = 32

//so:extern crypto_box_SEALBYTES
const Box_SEALBYTES = 48

//so:extern crypto_box_SECRETKEYBYTES
const Box_SECRETKEYBYTES = 32

//so:extern crypto_box_SEEDBYTES
const Box_SEEDBYTES = 32

//so:extern crypto_box_ZEROBYTES
const Box_ZEROBYTES = 32

//so:extern crypto_box_curve25519xchacha20poly1305_BEFORENMBYTES
const Box_curve25519xchacha20poly1305_BEFORENMBYTES = 32

//so:extern crypto_box_curve25519xchacha20poly1305_MACBYTES
const Box_curve25519xchacha20poly1305_MACBYTES = 16

//so:extern crypto_box_curve25519xchacha20poly1305_NONCEBYTES
const Box_curve25519xchacha20poly1305_NONCEBYTES = 24

//so:extern crypto_box_curve25519xchacha20poly1305_PUBLICKEYBYTES
const Box_curve25519xchacha20poly1305_PUBLICKEYBYTES = 32

//so:extern crypto_box_curve25519xchacha20poly1305_SEALBYTES
const Box_curve25519xchacha20poly1305_SEALBYTES = 48

//so:extern crypto_box_curve25519xchacha20poly1305_SECRETKEYBYTES
const Box_curve25519xchacha20poly1305_SECRETKEYBYTES = 32

//so:extern crypto_box_curve25519xchacha20poly1305_SEEDBYTES
const Box_curve25519xchacha20poly1305_SEEDBYTES = 32

//so:extern crypto_box_curve25519xsalsa20poly1305_BEFORENMBYTES
const Box_curve25519xsalsa20poly1305_BEFORENMBYTES = 32

//so:extern crypto_box_curve25519xsalsa20poly1305_BOXZEROBYTES
const Box_curve25519xsalsa20poly1305_BOXZEROBYTES = 16

//so:extern crypto_box_curve25519xsalsa20poly1305_MACBYTES
const Box_curve25519xsalsa20poly1305_MACBYTES = 16

//so:extern crypto_box_curve25519xsalsa20poly1305_NONCEBYTES
const Box_curve25519xsalsa20poly1305_NONCEBYTES = 24

//so:extern crypto_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES
const Box_curve25519xsalsa20poly1305_PUBLICKEYBYTES = 32

//so:extern crypto_box_curve25519xsalsa20poly1305_SECRETKEYBYTES
const Box_curve25519xsalsa20poly1305_SECRETKEYBYTES = 32

//so:extern crypto_box_curve25519xsalsa20poly1305_SEEDBYTES
const Box_curve25519xsalsa20poly1305_SEEDBYTES = 32

//so:extern crypto_box_curve25519xsalsa20poly1305_ZEROBYTES
const Box_curve25519xsalsa20poly1305_ZEROBYTES = 32

//so:extern crypto_core_ed25519_BYTES
const Core_ed25519_BYTES = 32

//so:extern crypto_core_ed25519_HASHBYTES
const Core_ed25519_HASHBYTES = 64

//so:extern crypto_core_ed25519_NONREDUCEDSCALARBYTES
const Core_ed25519_NONREDUCEDSCALARBYTES = 64

//so:extern crypto_core_ed25519_SCALARBYTES
const Core_ed25519_SCALARBYTES = 32

//so:extern crypto_core_ed25519_UNIFORMBYTES
const Core_ed25519_UNIFORMBYTES = 32

//so:extern crypto_core_hchacha20_CONSTBYTES
const Core_hchacha20_CONSTBYTES = 16

//so:extern crypto_core_hchacha20_INPUTBYTES
const Core_hchacha20_INPUTBYTES = 16

//so:extern crypto_core_hchacha20_KEYBYTES
const Core_hchacha20_KEYBYTES = 32

//so:extern crypto_core_hchacha20_OUTPUTBYTES
const Core_hchacha20_OUTPUTBYTES = 32

//so:extern crypto_core_hsalsa20_CONSTBYTES
const Core_hsalsa20_CONSTBYTES = 16

//so:extern crypto_core_hsalsa20_INPUTBYTES
const Core_hsalsa20_INPUTBYTES = 16

//so:extern crypto_core_hsalsa20_KEYBYTES
const Core_hsalsa20_KEYBYTES = 32

//so:extern crypto_core_hsalsa20_OUTPUTBYTES
const Core_hsalsa20_OUTPUTBYTES = 32

//so:extern crypto_core_ristretto255_BYTES
const Core_ristretto255_BYTES = 32

//so:extern crypto_core_ristretto255_HASHBYTES
const Core_ristretto255_HASHBYTES = 64

//so:extern crypto_core_ristretto255_NONREDUCEDSCALARBYTES
const Core_ristretto255_NONREDUCEDSCALARBYTES = 64

//so:extern crypto_core_ristretto255_SCALARBYTES
const Core_ristretto255_SCALARBYTES = 32

//so:extern crypto_core_salsa2012_CONSTBYTES
const Core_salsa2012_CONSTBYTES = 16

//so:extern crypto_core_salsa2012_INPUTBYTES
const Core_salsa2012_INPUTBYTES = 16

//so:extern crypto_core_salsa2012_KEYBYTES
const Core_salsa2012_KEYBYTES = 32

//so:extern crypto_core_salsa2012_OUTPUTBYTES
const Core_salsa2012_OUTPUTBYTES = 64

//so:extern crypto_core_salsa208_CONSTBYTES
const Core_salsa208_CONSTBYTES = 16

//so:extern crypto_core_salsa208_INPUTBYTES
const Core_salsa208_INPUTBYTES = 16

//so:extern crypto_core_salsa208_KEYBYTES
const Core_salsa208_KEYBYTES = 32

//so:extern crypto_core_salsa208_OUTPUTBYTES
const Core_salsa208_OUTPUTBYTES = 64

//so:extern crypto_core_salsa20_CONSTBYTES
const Core_salsa20_CONSTBYTES = 16

//so:extern crypto_core_salsa20_INPUTBYTES
const Core_salsa20_INPUTBYTES = 16

//so:extern crypto_core_salsa20_KEYBYTES
const Core_salsa20_KEYBYTES = 32

//so:extern crypto_core_salsa20_OUTPUTBYTES
const Core_salsa20_OUTPUTBYTES = 64

//so:extern crypto_generichash_BYTES
const Generichash_BYTES = 32

//so:extern crypto_generichash_BYTES_MAX
const Generichash_BYTES_MAX = 64

//so:extern crypto_generichash_BYTES_MIN
const Generichash_BYTES_MIN = 16

//so:extern crypto_generichash_KEYBYTES
const Generichash_KEYBYTES = 32

//so:extern crypto_generichash_KEYBYTES_MAX
const Generichash_KEYBYTES_MAX = 64

//so:extern crypto_generichash_KEYBYTES_MIN
const Generichash_KEYBYTES_MIN = 16

//so:extern crypto_generichash_blake2b_BYTES
const Generichash_blake2b_BYTES = 32

//so:extern crypto_generichash_blake2b_BYTES_MAX
const Generichash_blake2b_BYTES_MAX = 64

//so:extern crypto_generichash_blake2b_BYTES_MIN
const Generichash_blake2b_BYTES_MIN = 16

//so:extern crypto_generichash_blake2b_KEYBYTES
const Generichash_blake2b_KEYBYTES = 32

//so:extern crypto_generichash_blake2b_KEYBYTES_MAX
const Generichash_blake2b_KEYBYTES_MAX = 64

//so:extern crypto_generichash_blake2b_KEYBYTES_MIN
const Generichash_blake2b_KEYBYTES_MIN = 16

//so:extern crypto_generichash_blake2b_PERSONALBYTES
const Generichash_blake2b_PERSONALBYTES = 16

//so:extern crypto_generichash_blake2b_SALTBYTES
const Generichash_blake2b_SALTBYTES = 16

//so:extern crypto_hash_BYTES
const Hash_BYTES = 64

//so:extern crypto_hash_sha256_BYTES
const Hash_sha256_BYTES = 32

//so:extern crypto_hash_sha3256_BYTES
const Hash_sha3256_BYTES = 32

//so:extern crypto_hash_sha3512_BYTES
const Hash_sha3512_BYTES = 64

//so:extern crypto_hash_sha512_BYTES
const Hash_sha512_BYTES = 64

//so:extern crypto_ipcrypt_BYTES
const Ipcrypt_BYTES = 16

//so:extern crypto_ipcrypt_KEYBYTES
const Ipcrypt_KEYBYTES = 16

//so:extern crypto_ipcrypt_NDX_INPUTBYTES
const Ipcrypt_NDX_INPUTBYTES = 16

//so:extern crypto_ipcrypt_NDX_KEYBYTES
const Ipcrypt_NDX_KEYBYTES = 32

//so:extern crypto_ipcrypt_NDX_OUTPUTBYTES
const Ipcrypt_NDX_OUTPUTBYTES = 32

//so:extern crypto_ipcrypt_NDX_TWEAKBYTES
const Ipcrypt_NDX_TWEAKBYTES = 16

//so:extern crypto_ipcrypt_ND_INPUTBYTES
const Ipcrypt_ND_INPUTBYTES = 16

//so:extern crypto_ipcrypt_ND_KEYBYTES
const Ipcrypt_ND_KEYBYTES = 16

//so:extern crypto_ipcrypt_ND_OUTPUTBYTES
const Ipcrypt_ND_OUTPUTBYTES = 24

//so:extern crypto_ipcrypt_ND_TWEAKBYTES
const Ipcrypt_ND_TWEAKBYTES = 8

//so:extern crypto_ipcrypt_PFX_BYTES
const Ipcrypt_PFX_BYTES = 16

//so:extern crypto_ipcrypt_PFX_KEYBYTES
const Ipcrypt_PFX_KEYBYTES = 32

//so:extern crypto_kdf_BYTES_MAX
const Kdf_BYTES_MAX = 64

//so:extern crypto_kdf_BYTES_MIN
const Kdf_BYTES_MIN = 16

//so:extern crypto_kdf_CONTEXTBYTES
const Kdf_CONTEXTBYTES = 8

//so:extern crypto_kdf_KEYBYTES
const Kdf_KEYBYTES = 32

//so:extern crypto_kdf_blake2b_BYTES_MAX
const Kdf_blake2b_BYTES_MAX = 64

//so:extern crypto_kdf_blake2b_BYTES_MIN
const Kdf_blake2b_BYTES_MIN = 16

//so:extern crypto_kdf_blake2b_CONTEXTBYTES
const Kdf_blake2b_CONTEXTBYTES = 8

//so:extern crypto_kdf_blake2b_KEYBYTES
const Kdf_blake2b_KEYBYTES = 32

//so:extern crypto_kdf_hkdf_sha256_BYTES_MAX
const Kdf_hkdf_sha256_BYTES_MAX = 8160

//so:extern crypto_kdf_hkdf_sha256_BYTES_MIN
const Kdf_hkdf_sha256_BYTES_MIN = 0

//so:extern crypto_kdf_hkdf_sha256_KEYBYTES
const Kdf_hkdf_sha256_KEYBYTES = 32

//so:extern crypto_kdf_hkdf_sha512_BYTES_MAX
const Kdf_hkdf_sha512_BYTES_MAX = 16320

//so:extern crypto_kdf_hkdf_sha512_BYTES_MIN
const Kdf_hkdf_sha512_BYTES_MIN = 0

//so:extern crypto_kdf_hkdf_sha512_KEYBYTES
const Kdf_hkdf_sha512_KEYBYTES = 64

//so:extern crypto_kem_CIPHERTEXTBYTES
const Kem_CIPHERTEXTBYTES = 1120

//so:extern crypto_kem_PUBLICKEYBYTES
const Kem_PUBLICKEYBYTES = 1216

//so:extern crypto_kem_SECRETKEYBYTES
const Kem_SECRETKEYBYTES = 32

//so:extern crypto_kem_SEEDBYTES
const Kem_SEEDBYTES = 32

//so:extern crypto_kem_SHAREDSECRETBYTES
const Kem_SHAREDSECRETBYTES = 32

//so:extern crypto_kem_mlkem768_CIPHERTEXTBYTES
const Kem_mlkem768_CIPHERTEXTBYTES = 1088

//so:extern crypto_kem_mlkem768_PUBLICKEYBYTES
const Kem_mlkem768_PUBLICKEYBYTES = 1184

//so:extern crypto_kem_mlkem768_SECRETKEYBYTES
const Kem_mlkem768_SECRETKEYBYTES = 2400

//so:extern crypto_kem_mlkem768_SEEDBYTES
const Kem_mlkem768_SEEDBYTES = 64

//so:extern crypto_kem_mlkem768_SHAREDSECRETBYTES
const Kem_mlkem768_SHAREDSECRETBYTES = 32

//so:extern crypto_kem_xwing_CIPHERTEXTBYTES
const Kem_xwing_CIPHERTEXTBYTES = 1120

//so:extern crypto_kem_xwing_PUBLICKEYBYTES
const Kem_xwing_PUBLICKEYBYTES = 1216

//so:extern crypto_kem_xwing_SECRETKEYBYTES
const Kem_xwing_SECRETKEYBYTES = 32

//so:extern crypto_kem_xwing_SEEDBYTES
const Kem_xwing_SEEDBYTES = 32

//so:extern crypto_kem_xwing_SHAREDSECRETBYTES
const Kem_xwing_SHAREDSECRETBYTES = 32

//so:extern crypto_kx_PUBLICKEYBYTES
const Kx_PUBLICKEYBYTES = 32

//so:extern crypto_kx_SECRETKEYBYTES
const Kx_SECRETKEYBYTES = 32

//so:extern crypto_kx_SEEDBYTES
const Kx_SEEDBYTES = 32

//so:extern crypto_kx_SESSIONKEYBYTES
const Kx_SESSIONKEYBYTES = 32

//so:extern crypto_onetimeauth_BYTES
const Onetimeauth_BYTES = 16

//so:extern crypto_onetimeauth_KEYBYTES
const Onetimeauth_KEYBYTES = 32

//so:extern crypto_onetimeauth_poly1305_BYTES
const Onetimeauth_poly1305_BYTES = 16

//so:extern crypto_onetimeauth_poly1305_KEYBYTES
const Onetimeauth_poly1305_KEYBYTES = 32

//so:extern crypto_pwhash_ALG_ARGON2I13
const Pwhash_ALG_ARGON2I13 = 1

//so:extern crypto_pwhash_ALG_ARGON2ID13
const Pwhash_ALG_ARGON2ID13 = 2

//so:extern crypto_pwhash_ALG_DEFAULT
const Pwhash_ALG_DEFAULT = 2

//so:extern crypto_pwhash_BYTES_MIN
const Pwhash_BYTES_MIN = 16

//so:extern crypto_pwhash_MEMLIMIT_INTERACTIVE
const Pwhash_MEMLIMIT_INTERACTIVE = 67108864

//so:extern crypto_pwhash_MEMLIMIT_MAX
const Pwhash_MEMLIMIT_MAX = 4398046510080

//so:extern crypto_pwhash_MEMLIMIT_MIN
const Pwhash_MEMLIMIT_MIN = 8192

//so:extern crypto_pwhash_MEMLIMIT_MODERATE
const Pwhash_MEMLIMIT_MODERATE = 268435456

//so:extern crypto_pwhash_MEMLIMIT_SENSITIVE
const Pwhash_MEMLIMIT_SENSITIVE = 1073741824

//so:extern crypto_pwhash_OPSLIMIT_INTERACTIVE
const Pwhash_OPSLIMIT_INTERACTIVE = 2

//so:extern crypto_pwhash_OPSLIMIT_MAX
const Pwhash_OPSLIMIT_MAX = 4294967295

//so:extern crypto_pwhash_OPSLIMIT_MIN
const Pwhash_OPSLIMIT_MIN = 1

//so:extern crypto_pwhash_OPSLIMIT_MODERATE
const Pwhash_OPSLIMIT_MODERATE = 3

//so:extern crypto_pwhash_OPSLIMIT_SENSITIVE
const Pwhash_OPSLIMIT_SENSITIVE = 4

//so:extern crypto_pwhash_PASSWD_MAX
const Pwhash_PASSWD_MAX = 4294967295

//so:extern crypto_pwhash_PASSWD_MIN
const Pwhash_PASSWD_MIN = 0

//so:extern crypto_pwhash_SALTBYTES
const Pwhash_SALTBYTES = 16

//so:extern crypto_pwhash_STRBYTES
const Pwhash_STRBYTES = 128

//so:extern crypto_pwhash_argon2i_ALG_ARGON2I13
const Pwhash_argon2i_ALG_ARGON2I13 = 1

//so:extern crypto_pwhash_argon2i_BYTES_MIN
const Pwhash_argon2i_BYTES_MIN = 16

//so:extern crypto_pwhash_argon2i_MEMLIMIT_INTERACTIVE
const Pwhash_argon2i_MEMLIMIT_INTERACTIVE = 33554432

//so:extern crypto_pwhash_argon2i_MEMLIMIT_MAX
const Pwhash_argon2i_MEMLIMIT_MAX = 4398046510080

//so:extern crypto_pwhash_argon2i_MEMLIMIT_MIN
const Pwhash_argon2i_MEMLIMIT_MIN = 8192

//so:extern crypto_pwhash_argon2i_MEMLIMIT_MODERATE
const Pwhash_argon2i_MEMLIMIT_MODERATE = 134217728

//so:extern crypto_pwhash_argon2i_MEMLIMIT_SENSITIVE
const Pwhash_argon2i_MEMLIMIT_SENSITIVE = 536870912

//so:extern crypto_pwhash_argon2i_OPSLIMIT_INTERACTIVE
const Pwhash_argon2i_OPSLIMIT_INTERACTIVE = 4

//so:extern crypto_pwhash_argon2i_OPSLIMIT_MAX
const Pwhash_argon2i_OPSLIMIT_MAX = 4294967295

//so:extern crypto_pwhash_argon2i_OPSLIMIT_MIN
const Pwhash_argon2i_OPSLIMIT_MIN = 3

//so:extern crypto_pwhash_argon2i_OPSLIMIT_MODERATE
const Pwhash_argon2i_OPSLIMIT_MODERATE = 6

//so:extern crypto_pwhash_argon2i_OPSLIMIT_SENSITIVE
const Pwhash_argon2i_OPSLIMIT_SENSITIVE = 8

//so:extern crypto_pwhash_argon2i_PASSWD_MAX
const Pwhash_argon2i_PASSWD_MAX = 4294967295

//so:extern crypto_pwhash_argon2i_PASSWD_MIN
const Pwhash_argon2i_PASSWD_MIN = 0

//so:extern crypto_pwhash_argon2i_SALTBYTES
const Pwhash_argon2i_SALTBYTES = 16

//so:extern crypto_pwhash_argon2i_STRBYTES
const Pwhash_argon2i_STRBYTES = 128

//so:extern crypto_pwhash_argon2id_ALG_ARGON2ID13
const Pwhash_argon2id_ALG_ARGON2ID13 = 2

//so:extern crypto_pwhash_argon2id_BYTES_MIN
const Pwhash_argon2id_BYTES_MIN = 16

//so:extern crypto_pwhash_argon2id_MEMLIMIT_INTERACTIVE
const Pwhash_argon2id_MEMLIMIT_INTERACTIVE = 67108864

//so:extern crypto_pwhash_argon2id_MEMLIMIT_MAX
const Pwhash_argon2id_MEMLIMIT_MAX = 4398046510080

//so:extern crypto_pwhash_argon2id_MEMLIMIT_MIN
const Pwhash_argon2id_MEMLIMIT_MIN = 8192

//so:extern crypto_pwhash_argon2id_MEMLIMIT_MODERATE
const Pwhash_argon2id_MEMLIMIT_MODERATE = 268435456

//so:extern crypto_pwhash_argon2id_MEMLIMIT_SENSITIVE
const Pwhash_argon2id_MEMLIMIT_SENSITIVE = 1073741824

//so:extern crypto_pwhash_argon2id_OPSLIMIT_INTERACTIVE
const Pwhash_argon2id_OPSLIMIT_INTERACTIVE = 2

//so:extern crypto_pwhash_argon2id_OPSLIMIT_MAX
const Pwhash_argon2id_OPSLIMIT_MAX = 4294967295

//so:extern crypto_pwhash_argon2id_OPSLIMIT_MIN
const Pwhash_argon2id_OPSLIMIT_MIN = 1

//so:extern crypto_pwhash_argon2id_OPSLIMIT_MODERATE
const Pwhash_argon2id_OPSLIMIT_MODERATE = 3

//so:extern crypto_pwhash_argon2id_OPSLIMIT_SENSITIVE
const Pwhash_argon2id_OPSLIMIT_SENSITIVE = 4

//so:extern crypto_pwhash_argon2id_PASSWD_MAX
const Pwhash_argon2id_PASSWD_MAX = 4294967295

//so:extern crypto_pwhash_argon2id_PASSWD_MIN
const Pwhash_argon2id_PASSWD_MIN = 0

//so:extern crypto_pwhash_argon2id_SALTBYTES
const Pwhash_argon2id_SALTBYTES = 16

//so:extern crypto_pwhash_argon2id_STRBYTES
const Pwhash_argon2id_STRBYTES = 128

//so:extern crypto_pwhash_scryptsalsa208sha256_BYTES_MIN
const Pwhash_scryptsalsa208sha256_BYTES_MIN = 16

//so:extern crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_INTERACTIVE
const Pwhash_scryptsalsa208sha256_MEMLIMIT_INTERACTIVE = 16777216

//so:extern crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_MIN
const Pwhash_scryptsalsa208sha256_MEMLIMIT_MIN = 16777216

//so:extern crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE
const Pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE = 1073741824

//so:extern crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_INTERACTIVE
const Pwhash_scryptsalsa208sha256_OPSLIMIT_INTERACTIVE = 524288

//so:extern crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MAX
const Pwhash_scryptsalsa208sha256_OPSLIMIT_MAX = 4294967295

//so:extern crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MIN
const Pwhash_scryptsalsa208sha256_OPSLIMIT_MIN = 32768

//so:extern crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE
const Pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE = 33554432

//so:extern crypto_pwhash_scryptsalsa208sha256_PASSWD_MIN
const Pwhash_scryptsalsa208sha256_PASSWD_MIN = 0

//so:extern crypto_pwhash_scryptsalsa208sha256_SALTBYTES
const Pwhash_scryptsalsa208sha256_SALTBYTES = 32

//so:extern crypto_pwhash_scryptsalsa208sha256_STRBYTES
const Pwhash_scryptsalsa208sha256_STRBYTES = 102

//so:extern crypto_scalarmult_BYTES
const Scalarmult_BYTES = 32

//so:extern crypto_scalarmult_SCALARBYTES
const Scalarmult_SCALARBYTES = 32

//so:extern crypto_scalarmult_curve25519_BYTES
const Scalarmult_curve25519_BYTES = 32

//so:extern crypto_scalarmult_curve25519_SCALARBYTES
const Scalarmult_curve25519_SCALARBYTES = 32

//so:extern crypto_scalarmult_ed25519_BYTES
const Scalarmult_ed25519_BYTES = 32

//so:extern crypto_scalarmult_ed25519_SCALARBYTES
const Scalarmult_ed25519_SCALARBYTES = 32

//so:extern crypto_scalarmult_ristretto255_BYTES
const Scalarmult_ristretto255_BYTES = 32

//so:extern crypto_scalarmult_ristretto255_SCALARBYTES
const Scalarmult_ristretto255_SCALARBYTES = 32

//so:extern crypto_secretbox_BOXZEROBYTES
const Secretbox_BOXZEROBYTES = 16

//so:extern crypto_secretbox_KEYBYTES
const Secretbox_KEYBYTES = 32

//so:extern crypto_secretbox_MACBYTES
const Secretbox_MACBYTES = 16

//so:extern crypto_secretbox_NONCEBYTES
const Secretbox_NONCEBYTES = 24

//so:extern crypto_secretbox_ZEROBYTES
const Secretbox_ZEROBYTES = 32

//so:extern crypto_secretbox_xchacha20poly1305_KEYBYTES
const Secretbox_xchacha20poly1305_KEYBYTES = 32

//so:extern crypto_secretbox_xchacha20poly1305_MACBYTES
const Secretbox_xchacha20poly1305_MACBYTES = 16

//so:extern crypto_secretbox_xchacha20poly1305_NONCEBYTES
const Secretbox_xchacha20poly1305_NONCEBYTES = 24

//so:extern crypto_secretbox_xsalsa20poly1305_BOXZEROBYTES
const Secretbox_xsalsa20poly1305_BOXZEROBYTES = 16

//so:extern crypto_secretbox_xsalsa20poly1305_KEYBYTES
const Secretbox_xsalsa20poly1305_KEYBYTES = 32

//so:extern crypto_secretbox_xsalsa20poly1305_MACBYTES
const Secretbox_xsalsa20poly1305_MACBYTES = 16

//so:extern crypto_secretbox_xsalsa20poly1305_NONCEBYTES
const Secretbox_xsalsa20poly1305_NONCEBYTES = 24

//so:extern crypto_secretbox_xsalsa20poly1305_ZEROBYTES
const Secretbox_xsalsa20poly1305_ZEROBYTES = 32

//so:extern crypto_secretstream_xchacha20poly1305_ABYTES
const Secretstream_xchacha20poly1305_ABYTES = 17

//so:extern crypto_secretstream_xchacha20poly1305_HEADERBYTES
const Secretstream_xchacha20poly1305_HEADERBYTES = 24

//so:extern crypto_secretstream_xchacha20poly1305_KEYBYTES
const Secretstream_xchacha20poly1305_KEYBYTES = 32

//so:extern crypto_secretstream_xchacha20poly1305_TAG_FINAL
const Secretstream_xchacha20poly1305_TAG_FINAL = 3

//so:extern crypto_secretstream_xchacha20poly1305_TAG_MESSAGE
const Secretstream_xchacha20poly1305_TAG_MESSAGE = 0

//so:extern crypto_secretstream_xchacha20poly1305_TAG_PUSH
const Secretstream_xchacha20poly1305_TAG_PUSH = 1

//so:extern crypto_secretstream_xchacha20poly1305_TAG_REKEY
const Secretstream_xchacha20poly1305_TAG_REKEY = 2

//so:extern crypto_shorthash_BYTES
const Shorthash_BYTES = 8

//so:extern crypto_shorthash_KEYBYTES
const Shorthash_KEYBYTES = 16

//so:extern crypto_shorthash_siphash24_BYTES
const Shorthash_siphash24_BYTES = 8

//so:extern crypto_shorthash_siphash24_KEYBYTES
const Shorthash_siphash24_KEYBYTES = 16

//so:extern crypto_shorthash_siphashx24_BYTES
const Shorthash_siphashx24_BYTES = 16

//so:extern crypto_shorthash_siphashx24_KEYBYTES
const Shorthash_siphashx24_KEYBYTES = 16

//so:extern crypto_sign_BYTES
const Sign_BYTES = 64

//so:extern crypto_sign_PUBLICKEYBYTES
const Sign_PUBLICKEYBYTES = 32

//so:extern crypto_sign_SECRETKEYBYTES
const Sign_SECRETKEYBYTES = 64

//so:extern crypto_sign_SEEDBYTES
const Sign_SEEDBYTES = 32

//so:extern crypto_sign_ed25519_BYTES
const Sign_ed25519_BYTES = 64

//so:extern crypto_sign_ed25519_PUBLICKEYBYTES
const Sign_ed25519_PUBLICKEYBYTES = 32

//so:extern crypto_sign_ed25519_SECRETKEYBYTES
const Sign_ed25519_SECRETKEYBYTES = 64

//so:extern crypto_sign_ed25519_SEEDBYTES
const Sign_ed25519_SEEDBYTES = 32

//so:extern crypto_stream_KEYBYTES
const Stream_KEYBYTES = 32

//so:extern crypto_stream_NONCEBYTES
const Stream_NONCEBYTES = 24

//so:extern crypto_stream_chacha20_KEYBYTES
const Stream_chacha20_KEYBYTES = 32

//so:extern crypto_stream_chacha20_NONCEBYTES
const Stream_chacha20_NONCEBYTES = 8

//so:extern crypto_stream_chacha20_ietf_KEYBYTES
const Stream_chacha20_ietf_KEYBYTES = 32

//so:extern crypto_stream_chacha20_ietf_NONCEBYTES
const Stream_chacha20_ietf_NONCEBYTES = 12

//so:extern crypto_stream_salsa2012_KEYBYTES
const Stream_salsa2012_KEYBYTES = 32

//so:extern crypto_stream_salsa2012_NONCEBYTES
const Stream_salsa2012_NONCEBYTES = 8

//so:extern crypto_stream_salsa208_KEYBYTES
const Stream_salsa208_KEYBYTES = 32

//so:extern crypto_stream_salsa208_NONCEBYTES
const Stream_salsa208_NONCEBYTES = 8

//so:extern crypto_stream_salsa20_KEYBYTES
const Stream_salsa20_KEYBYTES = 32

//so:extern crypto_stream_salsa20_NONCEBYTES
const Stream_salsa20_NONCEBYTES = 8

//so:extern crypto_stream_xchacha20_KEYBYTES
const Stream_xchacha20_KEYBYTES = 32

//so:extern crypto_stream_xchacha20_NONCEBYTES
const Stream_xchacha20_NONCEBYTES = 24

//so:extern crypto_stream_xsalsa20_KEYBYTES
const Stream_xsalsa20_KEYBYTES = 32

//so:extern crypto_stream_xsalsa20_NONCEBYTES
const Stream_xsalsa20_NONCEBYTES = 24

//so:extern crypto_verify_16_BYTES
const Verify_16_BYTES = 16

//so:extern crypto_verify_32_BYTES
const Verify_32_BYTES = 32

//so:extern crypto_verify_64_BYTES
const Verify_64_BYTES = 64

//so:extern crypto_xof_shake128_BLOCKBYTES
const Xof_shake128_BLOCKBYTES = 168

//so:extern crypto_xof_shake128_DOMAIN_STANDARD
const Xof_shake128_DOMAIN_STANDARD = 31

//so:extern crypto_xof_shake128_STATEBYTES
const Xof_shake128_STATEBYTES = 256

//so:extern crypto_xof_shake256_BLOCKBYTES
const Xof_shake256_BLOCKBYTES = 136

//so:extern crypto_xof_shake256_DOMAIN_STANDARD
const Xof_shake256_DOMAIN_STANDARD = 31

//so:extern crypto_xof_shake256_STATEBYTES
const Xof_shake256_STATEBYTES = 256

//so:extern crypto_xof_turboshake128_BLOCKBYTES
const Xof_turboshake128_BLOCKBYTES = 168

//so:extern crypto_xof_turboshake128_DOMAIN_STANDARD
const Xof_turboshake128_DOMAIN_STANDARD = 31

//so:extern crypto_xof_turboshake128_STATEBYTES
const Xof_turboshake128_STATEBYTES = 256

//so:extern crypto_xof_turboshake256_BLOCKBYTES
const Xof_turboshake256_BLOCKBYTES = 136

//so:extern crypto_xof_turboshake256_DOMAIN_STANDARD
const Xof_turboshake256_DOMAIN_STANDARD = 31

//so:extern crypto_xof_turboshake256_STATEBYTES
const Xof_turboshake256_STATEBYTES = 256

//so:extern randombytes_SEEDBYTES
const Randombytes_SEEDBYTES = 32

//so:extern sodium_base64_VARIANT_ORIGINAL
const Base64_VARIANT_ORIGINAL = 1

//so:extern sodium_base64_VARIANT_ORIGINAL_NO_PADDING
const Base64_VARIANT_ORIGINAL_NO_PADDING = 3

//so:extern sodium_base64_VARIANT_URLSAFE
const Base64_VARIANT_URLSAFE = 5

//so:extern sodium_base64_VARIANT_URLSAFE_NO_PADDING
const Base64_VARIANT_URLSAFE_NO_PADDING = 7

//so:extern randombytes_internal_implementation
var Randombytes_internal_implementation Randombytes_implementation

//so:extern randombytes_sysrandom_implementation
var Randombytes_sysrandom_implementation Randombytes_implementation

//so:extern SODIUM_VERSION_STRING
var VERSION_STRING *c.ConstChar // "1.0.22"

//so:extern crypto_auth_PRIMITIVE
var Auth_PRIMITIVE *c.ConstChar // "hmacsha512256"

//so:extern crypto_box_PRIMITIVE
var Box_PRIMITIVE *c.ConstChar // "curve25519xsalsa20poly1305"

//so:extern crypto_generichash_PRIMITIVE
var Generichash_PRIMITIVE *c.ConstChar // "blake2b"

//so:extern crypto_hash_PRIMITIVE
var Hash_PRIMITIVE *c.ConstChar // "sha512"

//so:extern crypto_kdf_PRIMITIVE
var Kdf_PRIMITIVE *c.ConstChar // "blake2b"

//so:extern crypto_kem_PRIMITIVE
var Kem_PRIMITIVE *c.ConstChar // "xwing"

//so:extern crypto_kx_PRIMITIVE
var Kx_PRIMITIVE *c.ConstChar // "x25519blake2b"

//so:extern crypto_onetimeauth_PRIMITIVE
var Onetimeauth_PRIMITIVE *c.ConstChar // "poly1305"

//so:extern crypto_pwhash_PRIMITIVE
var Pwhash_PRIMITIVE *c.ConstChar // "argon2id,argon2i"

//so:extern crypto_pwhash_STRPREFIX
var Pwhash_STRPREFIX *c.ConstChar // "$argon2id$"

//so:extern crypto_pwhash_argon2i_STRPREFIX
var Pwhash_argon2i_STRPREFIX *c.ConstChar // "$argon2i$"

//so:extern crypto_pwhash_argon2id_STRPREFIX
var Pwhash_argon2id_STRPREFIX *c.ConstChar // "$argon2id$"

//so:extern crypto_pwhash_scryptsalsa208sha256_STRPREFIX
var Pwhash_scryptsalsa208sha256_STRPREFIX *c.ConstChar // "$7$"

//so:extern crypto_scalarmult_PRIMITIVE
var Scalarmult_PRIMITIVE *c.ConstChar // "curve25519"

//so:extern crypto_secretbox_PRIMITIVE
var Secretbox_PRIMITIVE *c.ConstChar // "xsalsa20poly1305"

//so:extern crypto_shorthash_PRIMITIVE
var Shorthash_PRIMITIVE *c.ConstChar // "siphash24"

//so:extern crypto_sign_PRIMITIVE
var Sign_PRIMITIVE *c.ConstChar // "ed25519"

//so:extern crypto_stream_PRIMITIVE
var Stream_PRIMITIVE *c.ConstChar // "xsalsa20"

//so:extern sodium_library_minimal
func Library_minimal() c.Int

//so:extern sodium_init
func Init() c.Int

//so:extern sodium_set_misuse_handler
func Set_misuse_handler(handler func()) c.Int

//so:extern sodium_misuse
func Misuse()

//so:extern crypto_aead_aegis128l_messagebytes_max
func Aead_aegis128l_messagebytes_max() c.Size

//so:extern crypto_aead_aegis128l_encrypt
func Aead_aegis128l_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis128l_decrypt
func Aead_aegis128l_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis128l_encrypt_detached
func Aead_aegis128l_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis128l_decrypt_detached
func Aead_aegis128l_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis128l_keygen
func Aead_aegis128l_keygen(k *c.UChar)

//so:extern crypto_aead_aegis256_messagebytes_max
func Aead_aegis256_messagebytes_max() c.Size

//so:extern crypto_aead_aegis256_encrypt
func Aead_aegis256_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis256_decrypt
func Aead_aegis256_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis256_encrypt_detached
func Aead_aegis256_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis256_decrypt_detached
func Aead_aegis256_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aegis256_keygen
func Aead_aegis256_keygen(k *c.UChar)

//so:extern crypto_aead_aes256gcm_is_available
func Aead_aes256gcm_is_available() c.Int

//so:extern crypto_aead_aes256gcm_messagebytes_max
func Aead_aes256gcm_messagebytes_max() c.Size

//so:extern crypto_aead_aes256gcm_statebytes
func Aead_aes256gcm_statebytes() c.Size

//so:extern crypto_aead_aes256gcm_encrypt
func Aead_aes256gcm_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aes256gcm_decrypt
func Aead_aes256gcm_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aes256gcm_encrypt_detached
func Aead_aes256gcm_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aes256gcm_decrypt_detached
func Aead_aes256gcm_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_aes256gcm_beforenm
func Aead_aes256gcm_beforenm(ctx_ *Aead_aes256gcm_state, k *c.UChar) c.Int

//so:extern crypto_aead_aes256gcm_encrypt_afternm
func Aead_aes256gcm_encrypt_afternm(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, ctx_ *Aead_aes256gcm_state) c.Int

//so:extern crypto_aead_aes256gcm_decrypt_afternm
func Aead_aes256gcm_decrypt_afternm(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, ctx_ *Aead_aes256gcm_state) c.Int

//so:extern crypto_aead_aes256gcm_encrypt_detached_afternm
func Aead_aes256gcm_encrypt_detached_afternm(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, ctx_ *Aead_aes256gcm_state) c.Int

//so:extern crypto_aead_aes256gcm_decrypt_detached_afternm
func Aead_aes256gcm_decrypt_detached_afternm(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, ctx_ *Aead_aes256gcm_state) c.Int

//so:extern crypto_aead_aes256gcm_keygen
func Aead_aes256gcm_keygen(k *c.UChar)

//so:extern crypto_aead_chacha20poly1305_ietf_messagebytes_max
func Aead_chacha20poly1305_ietf_messagebytes_max() c.Size

//so:extern crypto_aead_chacha20poly1305_ietf_encrypt
func Aead_chacha20poly1305_ietf_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_ietf_decrypt
func Aead_chacha20poly1305_ietf_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_ietf_encrypt_detached
func Aead_chacha20poly1305_ietf_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_ietf_decrypt_detached
func Aead_chacha20poly1305_ietf_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_ietf_keygen
func Aead_chacha20poly1305_ietf_keygen(k *c.UChar)

//so:extern crypto_aead_chacha20poly1305_messagebytes_max
func Aead_chacha20poly1305_messagebytes_max() c.Size

//so:extern crypto_aead_chacha20poly1305_encrypt
func Aead_chacha20poly1305_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_decrypt
func Aead_chacha20poly1305_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_encrypt_detached
func Aead_chacha20poly1305_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_decrypt_detached
func Aead_chacha20poly1305_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_chacha20poly1305_keygen
func Aead_chacha20poly1305_keygen(k *c.UChar)

//so:extern crypto_aead_xchacha20poly1305_ietf_messagebytes_max
func Aead_xchacha20poly1305_ietf_messagebytes_max() c.Size

//so:extern crypto_aead_xchacha20poly1305_ietf_encrypt
func Aead_xchacha20poly1305_ietf_encrypt(c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_xchacha20poly1305_ietf_decrypt
func Aead_xchacha20poly1305_ietf_decrypt(m *c.UChar, mlen_p *c.ULongLong, nsec *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_xchacha20poly1305_ietf_encrypt_detached
func Aead_xchacha20poly1305_ietf_encrypt_detached(c *c.UChar, mac *c.UChar, maclen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, nsec *c.UChar, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_xchacha20poly1305_ietf_decrypt_detached
func Aead_xchacha20poly1305_ietf_decrypt_detached(m *c.UChar, nsec *c.UChar, c *c.UChar, clen c.ULongLong, mac *c.UChar, ad *c.UChar, adlen c.ULongLong, npub *c.UChar, k *c.UChar) c.Int

//so:extern crypto_aead_xchacha20poly1305_ietf_keygen
func Aead_xchacha20poly1305_ietf_keygen(k *c.UChar)

//so:extern crypto_hash_sha512_statebytes
func Hash_sha512_statebytes() c.Size

//so:extern crypto_hash_sha512
func Hash_sha512(out *c.UChar, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha512_init
func Hash_sha512_init(state *Hash_sha512_state) c.Int

//so:extern crypto_hash_sha512_update
func Hash_sha512_update(state *Hash_sha512_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha512_final
func Hash_sha512_final(state *Hash_sha512_state, out *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512
func Auth_hmacsha512(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512_verify
func Auth_hmacsha512_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512_statebytes
func Auth_hmacsha512_statebytes() c.Size

//so:extern crypto_auth_hmacsha512_init
func Auth_hmacsha512_init(state *Auth_hmacsha512_state, key *c.UChar, keylen c.Size) c.Int

//so:extern crypto_auth_hmacsha512_update
func Auth_hmacsha512_update(state *Auth_hmacsha512_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_auth_hmacsha512_final
func Auth_hmacsha512_final(state *Auth_hmacsha512_state, out *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512_keygen
func Auth_hmacsha512_keygen(k *c.UChar)

//so:extern crypto_auth_hmacsha512256
func Auth_hmacsha512256(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512256_verify
func Auth_hmacsha512256_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512256_statebytes
func Auth_hmacsha512256_statebytes() c.Size

//so:extern crypto_auth_hmacsha512256_init
func Auth_hmacsha512256_init(state *Auth_hmacsha512256_state, key *c.UChar, keylen c.Size) c.Int

//so:extern crypto_auth_hmacsha512256_update
func Auth_hmacsha512256_update(state *Auth_hmacsha512256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_auth_hmacsha512256_final
func Auth_hmacsha512256_final(state *Auth_hmacsha512256_state, out *c.UChar) c.Int

//so:extern crypto_auth_hmacsha512256_keygen
func Auth_hmacsha512256_keygen(k *c.UChar)

//so:extern crypto_auth
func Auth(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_verify
func Auth_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_keygen
func Auth_keygen(k *c.UChar)

//so:extern crypto_hash_sha256_statebytes
func Hash_sha256_statebytes() c.Size

//so:extern crypto_hash_sha256
func Hash_sha256(out *c.UChar, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha256_init
func Hash_sha256_init(state *Hash_sha256_state) c.Int

//so:extern crypto_hash_sha256_update
func Hash_sha256_update(state *Hash_sha256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha256_final
func Hash_sha256_final(state *Hash_sha256_state, out *c.UChar) c.Int

//so:extern crypto_auth_hmacsha256
func Auth_hmacsha256(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha256_verify
func Auth_hmacsha256_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_auth_hmacsha256_statebytes
func Auth_hmacsha256_statebytes() c.Size

//so:extern crypto_auth_hmacsha256_init
func Auth_hmacsha256_init(state *Auth_hmacsha256_state, key *c.UChar, keylen c.Size) c.Int

//so:extern crypto_auth_hmacsha256_update
func Auth_hmacsha256_update(state *Auth_hmacsha256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_auth_hmacsha256_final
func Auth_hmacsha256_final(state *Auth_hmacsha256_state, out *c.UChar) c.Int

//so:extern crypto_auth_hmacsha256_keygen
func Auth_hmacsha256_keygen(k *c.UChar)

//so:extern crypto_stream_xsalsa20_messagebytes_max
func Stream_xsalsa20_messagebytes_max() c.Size

//so:extern crypto_stream_xsalsa20
func Stream_xsalsa20(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_xsalsa20_xor
func Stream_xsalsa20_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_xsalsa20_xor_ic
func Stream_xsalsa20_xor_ic(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, ic uint64, k *c.UChar) c.Int

//so:extern crypto_stream_xsalsa20_keygen
func Stream_xsalsa20_keygen(k *c.UChar)

//so:extern crypto_box_curve25519xsalsa20poly1305_messagebytes_max
func Box_curve25519xsalsa20poly1305_messagebytes_max() c.Size

//so:extern crypto_box_curve25519xsalsa20poly1305_seed_keypair
func Box_curve25519xsalsa20poly1305_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305_keypair
func Box_curve25519xsalsa20poly1305_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305_beforenm
func Box_curve25519xsalsa20poly1305_beforenm(k *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305
func Box_curve25519xsalsa20poly1305(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305_open
func Box_curve25519xsalsa20poly1305_open(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305_afternm
func Box_curve25519xsalsa20poly1305_afternm(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_curve25519xsalsa20poly1305_open_afternm
func Box_curve25519xsalsa20poly1305_open_afternm(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_messagebytes_max
func Box_messagebytes_max() c.Size

//so:extern crypto_box_seed_keypair
func Box_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_box_keypair
func Box_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_easy
func Box_easy(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_open_easy
func Box_open_easy(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_detached
func Box_detached(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_open_detached
func Box_open_detached(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_beforenm
func Box_beforenm(k *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_easy_afternm
func Box_easy_afternm(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_open_easy_afternm
func Box_open_easy_afternm(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_detached_afternm
func Box_detached_afternm(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_open_detached_afternm
func Box_open_detached_afternm(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_seal
func Box_seal(c *c.UChar, m *c.UChar, mlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_box_seal_open
func Box_seal_open(m *c.UChar, c *c.UChar, clen c.ULongLong, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box
func Box(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_open
func Box_open(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_afternm
func Box_afternm(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_open_afternm
func Box_open_afternm(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_core_hchacha20
func Core_hchacha20(out *c.UChar, in *c.UChar, k *c.UChar, c *c.UChar) c.Int

//so:extern crypto_core_hsalsa20
func Core_hsalsa20(out *c.UChar, in *c.UChar, k *c.UChar, c *c.UChar) c.Int

//so:extern crypto_core_keccak1600_statebytes
func Core_keccak1600_statebytes() c.Size

//so:extern crypto_core_keccak1600_init
func Core_keccak1600_init(state *Core_keccak1600_state)

//so:extern crypto_core_keccak1600_xor_bytes
func Core_keccak1600_xor_bytes(state *Core_keccak1600_state, bytes *c.UChar, offset c.Size, length c.Size)

//so:extern crypto_core_keccak1600_extract_bytes
func Core_keccak1600_extract_bytes(state *Core_keccak1600_state, bytes *c.UChar, offset c.Size, length c.Size)

//so:extern crypto_core_keccak1600_permute_24
func Core_keccak1600_permute_24(state *Core_keccak1600_state)

//so:extern crypto_core_keccak1600_permute_12
func Core_keccak1600_permute_12(state *Core_keccak1600_state)

//so:extern crypto_core_salsa20
func Core_salsa20(out *c.UChar, in *c.UChar, k *c.UChar, c *c.UChar) c.Int

//so:extern crypto_core_salsa2012
func Core_salsa2012(out *c.UChar, in *c.UChar, k *c.UChar, c *c.UChar) c.Int

//so:extern crypto_core_salsa208
func Core_salsa208(out *c.UChar, in *c.UChar, k *c.UChar, c *c.UChar) c.Int

//so:extern crypto_generichash_blake2b_statebytes
func Generichash_blake2b_statebytes() c.Size

//so:extern crypto_generichash_blake2b
func Generichash_blake2b(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong, key *c.UChar, keylen c.Size) c.Int

//so:extern crypto_generichash_blake2b_salt_personal
func Generichash_blake2b_salt_personal(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong, key *c.UChar, keylen c.Size, salt *c.UChar, personal *c.UChar) c.Int

//so:extern crypto_generichash_blake2b_init
func Generichash_blake2b_init(state *Generichash_blake2b_state, key *c.UChar, keylen c.Size, outlen c.Size) c.Int

//so:extern crypto_generichash_blake2b_init_salt_personal
func Generichash_blake2b_init_salt_personal(state *Generichash_blake2b_state, key *c.UChar, keylen c.Size, outlen c.Size, salt *c.UChar, personal *c.UChar) c.Int

//so:extern crypto_generichash_blake2b_update
func Generichash_blake2b_update(state *Generichash_blake2b_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_generichash_blake2b_final
func Generichash_blake2b_final(state *Generichash_blake2b_state, out *c.UChar, outlen c.Size) c.Int

//so:extern crypto_generichash_blake2b_keygen
func Generichash_blake2b_keygen(k *c.UChar)

//so:extern crypto_generichash_statebytes
func Generichash_statebytes() c.Size

//so:extern crypto_generichash
func Generichash(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong, key *c.UChar, keylen c.Size) c.Int

//so:extern crypto_generichash_init
func Generichash_init(state *Generichash_state, key *c.UChar, keylen c.Size, outlen c.Size) c.Int

//so:extern crypto_generichash_update
func Generichash_update(state *Generichash_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_generichash_final
func Generichash_final(state *Generichash_state, out *c.UChar, outlen c.Size) c.Int

//so:extern crypto_generichash_keygen
func Generichash_keygen(k *c.UChar)

//so:extern crypto_hash
func Hash(out *c.UChar, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha3256_statebytes
func Hash_sha3256_statebytes() c.Size

//so:extern crypto_hash_sha3256
func Hash_sha3256(out *c.UChar, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha3256_init
func Hash_sha3256_init(state *Hash_sha3256_state) c.Int

//so:extern crypto_hash_sha3256_update
func Hash_sha3256_update(state *Hash_sha3256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha3256_final
func Hash_sha3256_final(state *Hash_sha3256_state, out *c.UChar) c.Int

//so:extern crypto_hash_sha3512_statebytes
func Hash_sha3512_statebytes() c.Size

//so:extern crypto_hash_sha3512
func Hash_sha3512(out *c.UChar, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha3512_init
func Hash_sha3512_init(state *Hash_sha3512_state) c.Int

//so:extern crypto_hash_sha3512_update
func Hash_sha3512_update(state *Hash_sha3512_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_hash_sha3512_final
func Hash_sha3512_final(state *Hash_sha3512_state, out *c.UChar) c.Int

//so:extern crypto_ipcrypt_keygen
func Ipcrypt_keygen(k *c.UChar)

//so:extern crypto_ipcrypt_nd_keygen
func Ipcrypt_nd_keygen(k *c.UChar)

//so:extern crypto_ipcrypt_ndx_keygen
func Ipcrypt_ndx_keygen(k *c.UChar)

//so:extern crypto_ipcrypt_pfx_keygen
func Ipcrypt_pfx_keygen(k *c.UChar)

//so:extern crypto_ipcrypt_encrypt
func Ipcrypt_encrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_decrypt
func Ipcrypt_decrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_nd_encrypt
func Ipcrypt_nd_encrypt(out *c.UChar, in *c.UChar, t *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_nd_decrypt
func Ipcrypt_nd_decrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_ndx_encrypt
func Ipcrypt_ndx_encrypt(out *c.UChar, in *c.UChar, t *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_ndx_decrypt
func Ipcrypt_ndx_decrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_pfx_encrypt
func Ipcrypt_pfx_encrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_ipcrypt_pfx_decrypt
func Ipcrypt_pfx_decrypt(out *c.UChar, in *c.UChar, k *c.UChar)

//so:extern crypto_kdf_blake2b_derive_from_key
func Kdf_blake2b_derive_from_key(subkey *c.UChar, subkey_len c.Size, subkey_id uint64, ctx string, key *c.UChar) c.Int

//so:extern crypto_kdf_derive_from_key
func Kdf_derive_from_key(subkey *c.UChar, subkey_len c.Size, subkey_id uint64, ctx string, key *c.UChar) c.Int

//so:extern crypto_kdf_keygen
func Kdf_keygen(k *c.UChar)

//so:extern crypto_kdf_hkdf_sha256_extract
func Kdf_hkdf_sha256_extract(prk *c.UChar, salt *c.UChar, salt_len c.Size, ikm *c.UChar, ikm_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha256_keygen
func Kdf_hkdf_sha256_keygen(prk *c.UChar)

//so:extern crypto_kdf_hkdf_sha256_expand
func Kdf_hkdf_sha256_expand(out *c.UChar, out_len c.Size, ctx string, ctx_len c.Size, prk *c.UChar) c.Int

//so:extern crypto_kdf_hkdf_sha256_statebytes
func Kdf_hkdf_sha256_statebytes() c.Size

//so:extern crypto_kdf_hkdf_sha256_extract_init
func Kdf_hkdf_sha256_extract_init(state *Kdf_hkdf_sha256_state, salt *c.UChar, salt_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha256_extract_update
func Kdf_hkdf_sha256_extract_update(state *Kdf_hkdf_sha256_state, ikm *c.UChar, ikm_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha256_extract_final
func Kdf_hkdf_sha256_extract_final(state *Kdf_hkdf_sha256_state, prk *c.UChar) c.Int

//so:extern crypto_kdf_hkdf_sha512_extract
func Kdf_hkdf_sha512_extract(prk *c.UChar, salt *c.UChar, salt_len c.Size, ikm *c.UChar, ikm_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha512_keygen
func Kdf_hkdf_sha512_keygen(prk *c.UChar)

//so:extern crypto_kdf_hkdf_sha512_expand
func Kdf_hkdf_sha512_expand(out *c.UChar, out_len c.Size, ctx string, ctx_len c.Size, prk *c.UChar) c.Int

//so:extern crypto_kdf_hkdf_sha512_statebytes
func Kdf_hkdf_sha512_statebytes() c.Size

//so:extern crypto_kdf_hkdf_sha512_extract_init
func Kdf_hkdf_sha512_extract_init(state *Kdf_hkdf_sha512_state, salt *c.UChar, salt_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha512_extract_update
func Kdf_hkdf_sha512_extract_update(state *Kdf_hkdf_sha512_state, ikm *c.UChar, ikm_len c.Size) c.Int

//so:extern crypto_kdf_hkdf_sha512_extract_final
func Kdf_hkdf_sha512_extract_final(state *Kdf_hkdf_sha512_state, prk *c.UChar) c.Int

//so:extern crypto_kem_xwing_seed_keypair
func Kem_xwing_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kem_xwing_keypair
func Kem_xwing_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kem_xwing_enc
func Kem_xwing_enc(ct *c.UChar, ss *c.UChar, pk *c.UChar) c.Int

//so:extern crypto_kem_xwing_enc_deterministic
func Kem_xwing_enc_deterministic(ct *c.UChar, ss *c.UChar, pk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kem_xwing_dec
func Kem_xwing_dec(ss *c.UChar, ct *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kem_seed_keypair
func Kem_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kem_keypair
func Kem_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kem_enc
func Kem_enc(ct *c.UChar, ss *c.UChar, pk *c.UChar) c.Int

//so:extern crypto_kem_dec
func Kem_dec(ss *c.UChar, ct *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kem_mlkem768_seed_keypair
func Kem_mlkem768_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kem_mlkem768_keypair
func Kem_mlkem768_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kem_mlkem768_enc
func Kem_mlkem768_enc(ct *c.UChar, ss *c.UChar, pk *c.UChar) c.Int

//so:extern crypto_kem_mlkem768_enc_deterministic
func Kem_mlkem768_enc_deterministic(ct *c.UChar, ss *c.UChar, pk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kem_mlkem768_dec
func Kem_mlkem768_dec(ss *c.UChar, ct *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kx_seed_keypair
func Kx_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_kx_keypair
func Kx_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_kx_client_session_keys
func Kx_client_session_keys(rx *c.UChar, tx *c.UChar, client_pk *c.UChar, client_sk *c.UChar, server_pk *c.UChar) c.Int

//so:extern crypto_kx_server_session_keys
func Kx_server_session_keys(rx *c.UChar, tx *c.UChar, server_pk *c.UChar, server_sk *c.UChar, client_pk *c.UChar) c.Int

//so:extern crypto_onetimeauth_poly1305_statebytes
func Onetimeauth_poly1305_statebytes() c.Size

//so:extern crypto_onetimeauth_poly1305
func Onetimeauth_poly1305(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_onetimeauth_poly1305_verify
func Onetimeauth_poly1305_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_onetimeauth_poly1305_init
func Onetimeauth_poly1305_init(state *Onetimeauth_poly1305_state, key *c.UChar) c.Int

//so:extern crypto_onetimeauth_poly1305_update
func Onetimeauth_poly1305_update(state *Onetimeauth_poly1305_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_onetimeauth_poly1305_final
func Onetimeauth_poly1305_final(state *Onetimeauth_poly1305_state, out *c.UChar) c.Int

//so:extern crypto_onetimeauth_poly1305_keygen
func Onetimeauth_poly1305_keygen(k *c.UChar)

//so:extern crypto_onetimeauth_statebytes
func Onetimeauth_statebytes() c.Size

//so:extern crypto_onetimeauth
func Onetimeauth(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_onetimeauth_verify
func Onetimeauth_verify(h *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_onetimeauth_init
func Onetimeauth_init(state *Onetimeauth_state, key *c.UChar) c.Int

//so:extern crypto_onetimeauth_update
func Onetimeauth_update(state *Onetimeauth_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_onetimeauth_final
func Onetimeauth_final(state *Onetimeauth_state, out *c.UChar) c.Int

//so:extern crypto_onetimeauth_keygen
func Onetimeauth_keygen(k *c.UChar)

//so:extern crypto_pwhash_argon2i_bytes_max
func Pwhash_argon2i_bytes_max() c.Size

//so:extern crypto_pwhash_argon2i
func Pwhash_argon2i(out *c.UChar, outlen c.ULongLong, passwd string, passwdlen c.ULongLong, salt *c.UChar, opslimit c.ULongLong, memlimit c.Size, alg c.Int) c.Int

//so:extern crypto_pwhash_argon2i_str
func Pwhash_argon2i_str(out *c.Char, passwd string, passwdlen c.ULongLong, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_argon2i_str_verify
func Pwhash_argon2i_str_verify(str string, passwd string, passwdlen c.ULongLong) c.Int

//so:extern crypto_pwhash_argon2i_str_needs_rehash
func Pwhash_argon2i_str_needs_rehash(str string, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_argon2id_bytes_max
func Pwhash_argon2id_bytes_max() c.Size

//so:extern crypto_pwhash_argon2id
func Pwhash_argon2id(out *c.UChar, outlen c.ULongLong, passwd string, passwdlen c.ULongLong, salt *c.UChar, opslimit c.ULongLong, memlimit c.Size, alg c.Int) c.Int

//so:extern crypto_pwhash_argon2id_str
func Pwhash_argon2id_str(out *c.Char, passwd string, passwdlen c.ULongLong, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_argon2id_str_verify
func Pwhash_argon2id_str_verify(str string, passwd string, passwdlen c.ULongLong) c.Int

//so:extern crypto_pwhash_argon2id_str_needs_rehash
func Pwhash_argon2id_str_needs_rehash(str string, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_bytes_max
func Pwhash_bytes_max() c.Size

//so:extern crypto_pwhash
func Pwhash(out *c.UChar, outlen c.ULongLong, passwd string, passwdlen c.ULongLong, salt *c.UChar, opslimit c.ULongLong, memlimit c.Size, alg c.Int) c.Int

//so:extern crypto_pwhash_str
func Pwhash_str(out *c.Char, passwd string, passwdlen c.ULongLong, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_str_alg
func Pwhash_str_alg(out *c.Char, passwd string, passwdlen c.ULongLong, opslimit c.ULongLong, memlimit c.Size, alg c.Int) c.Int

//so:extern crypto_pwhash_str_verify
func Pwhash_str_verify(str string, passwd string, passwdlen c.ULongLong) c.Int

//so:extern crypto_pwhash_str_needs_rehash
func Pwhash_str_needs_rehash(str string, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_scalarmult_curve25519
func Scalarmult_curve25519(q *c.UChar, n *c.UChar, p *c.UChar) c.Int

//so:extern crypto_scalarmult_curve25519_base
func Scalarmult_curve25519_base(q *c.UChar, n *c.UChar) c.Int

//so:extern crypto_scalarmult_base
func Scalarmult_base(q *c.UChar, n *c.UChar) c.Int

//so:extern crypto_scalarmult
func Scalarmult(q *c.UChar, n *c.UChar, p *c.UChar) c.Int

//so:extern crypto_secretbox_xsalsa20poly1305_messagebytes_max
func Secretbox_xsalsa20poly1305_messagebytes_max() c.Size

//so:extern crypto_secretbox_xsalsa20poly1305
func Secretbox_xsalsa20poly1305(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_xsalsa20poly1305_open
func Secretbox_xsalsa20poly1305_open(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_xsalsa20poly1305_keygen
func Secretbox_xsalsa20poly1305_keygen(k *c.UChar)

//so:extern crypto_secretbox_messagebytes_max
func Secretbox_messagebytes_max() c.Size

//so:extern crypto_secretbox_easy
func Secretbox_easy(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_open_easy
func Secretbox_open_easy(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_detached
func Secretbox_detached(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_open_detached
func Secretbox_open_detached(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_keygen
func Secretbox_keygen(k *c.UChar)

//so:extern crypto_secretbox
func Secretbox(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_open
func Secretbox_open(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_messagebytes_max
func Stream_chacha20_messagebytes_max() c.Size

//so:extern crypto_stream_chacha20
func Stream_chacha20(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_xor
func Stream_chacha20_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_xor_ic
func Stream_chacha20_xor_ic(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, ic uint64, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_keygen
func Stream_chacha20_keygen(k *c.UChar)

//so:extern crypto_stream_chacha20_ietf_messagebytes_max
func Stream_chacha20_ietf_messagebytes_max() c.Size

//so:extern crypto_stream_chacha20_ietf
func Stream_chacha20_ietf(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_ietf_xor
func Stream_chacha20_ietf_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_ietf_xor_ic
func Stream_chacha20_ietf_xor_ic(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, ic uint32, k *c.UChar) c.Int

//so:extern crypto_stream_chacha20_ietf_keygen
func Stream_chacha20_ietf_keygen(k *c.UChar)

//so:extern crypto_secretstream_xchacha20poly1305_messagebytes_max
func Secretstream_xchacha20poly1305_messagebytes_max() c.Size

//so:extern crypto_secretstream_xchacha20poly1305_statebytes
func Secretstream_xchacha20poly1305_statebytes() c.Size

//so:extern crypto_secretstream_xchacha20poly1305_keygen
func Secretstream_xchacha20poly1305_keygen(k *c.UChar)

//so:extern crypto_secretstream_xchacha20poly1305_init_push
func Secretstream_xchacha20poly1305_init_push(state *Secretstream_xchacha20poly1305_state, header *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretstream_xchacha20poly1305_push
func Secretstream_xchacha20poly1305_push(state *Secretstream_xchacha20poly1305_state, c *c.UChar, clen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, ad *c.UChar, adlen c.ULongLong, tag c.UChar) c.Int

//so:extern crypto_secretstream_xchacha20poly1305_init_pull
func Secretstream_xchacha20poly1305_init_pull(state *Secretstream_xchacha20poly1305_state, header *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretstream_xchacha20poly1305_pull
func Secretstream_xchacha20poly1305_pull(state *Secretstream_xchacha20poly1305_state, m *c.UChar, mlen_p *c.ULongLong, tag_p *c.UChar, c *c.UChar, clen c.ULongLong, ad *c.UChar, adlen c.ULongLong) c.Int

//so:extern crypto_secretstream_xchacha20poly1305_rekey
func Secretstream_xchacha20poly1305_rekey(state *Secretstream_xchacha20poly1305_state)

//so:extern crypto_shorthash_siphash24
func Shorthash_siphash24(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_shorthash_siphashx24
func Shorthash_siphashx24(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_shorthash
func Shorthash(out *c.UChar, in *c.UChar, inlen c.ULongLong, k *c.UChar) c.Int

//so:extern crypto_shorthash_keygen
func Shorthash_keygen(k *c.UChar)

//so:extern crypto_sign_ed25519ph_statebytes
func Sign_ed25519ph_statebytes() c.Size

//so:extern crypto_sign_ed25519_messagebytes_max
func Sign_ed25519_messagebytes_max() c.Size

//so:extern crypto_sign_ed25519
func Sign_ed25519(sm *c.UChar, smlen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_open
func Sign_ed25519_open(m *c.UChar, mlen_p *c.ULongLong, sm *c.UChar, smlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_detached
func Sign_ed25519_detached(sig *c.UChar, siglen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_verify_detached
func Sign_ed25519_verify_detached(sig *c.UChar, m *c.UChar, mlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_keypair
func Sign_ed25519_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_seed_keypair
func Sign_ed25519_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_sign_ed25519_pk_to_curve25519
func Sign_ed25519_pk_to_curve25519(curve25519_pk *c.UChar, ed25519_pk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_sk_to_curve25519
func Sign_ed25519_sk_to_curve25519(curve25519_sk *c.UChar, ed25519_sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_sk_to_seed
func Sign_ed25519_sk_to_seed(seed *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519_sk_to_pk
func Sign_ed25519_sk_to_pk(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519ph_init
func Sign_ed25519ph_init(state *Sign_ed25519ph_state) c.Int

//so:extern crypto_sign_ed25519ph_update
func Sign_ed25519ph_update(state *Sign_ed25519ph_state, m *c.UChar, mlen c.ULongLong) c.Int

//so:extern crypto_sign_ed25519ph_final_create
func Sign_ed25519ph_final_create(state *Sign_ed25519ph_state, sig *c.UChar, siglen_p *c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_ed25519ph_final_verify
func Sign_ed25519ph_final_verify(state *Sign_ed25519ph_state, sig *c.UChar, pk *c.UChar) c.Int

//so:extern crypto_sign_statebytes
func Sign_statebytes() c.Size

//so:extern crypto_sign_messagebytes_max
func Sign_messagebytes_max() c.Size

//so:extern crypto_sign_seed_keypair
func Sign_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_sign_keypair
func Sign_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_sign
func Sign(sm *c.UChar, smlen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_open
func Sign_open(m *c.UChar, mlen_p *c.ULongLong, sm *c.UChar, smlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_sign_detached
func Sign_detached(sig *c.UChar, siglen_p *c.ULongLong, m *c.UChar, mlen c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_verify_detached
func Sign_verify_detached(sig *c.UChar, m *c.UChar, mlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_sign_init
func Sign_init(state *Sign_state) c.Int

//so:extern crypto_sign_update
func Sign_update(state *Sign_state, m *c.UChar, mlen c.ULongLong) c.Int

//so:extern crypto_sign_final_create
func Sign_final_create(state *Sign_state, sig *c.UChar, siglen_p *c.ULongLong, sk *c.UChar) c.Int

//so:extern crypto_sign_final_verify
func Sign_final_verify(state *Sign_state, sig *c.UChar, pk *c.UChar) c.Int

//so:extern crypto_stream_messagebytes_max
func Stream_messagebytes_max() c.Size

//so:extern crypto_stream
func Stream(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_xor
func Stream_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_keygen
func Stream_keygen(k *c.UChar)

//so:extern crypto_stream_salsa20_messagebytes_max
func Stream_salsa20_messagebytes_max() c.Size

//so:extern crypto_stream_salsa20
func Stream_salsa20(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa20_xor
func Stream_salsa20_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa20_xor_ic
func Stream_salsa20_xor_ic(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, ic uint64, k *c.UChar) c.Int

//so:extern crypto_stream_salsa20_keygen
func Stream_salsa20_keygen(k *c.UChar)

//so:extern crypto_verify_16
func Verify_16(x *c.UChar, y *c.UChar) c.Int

//so:extern crypto_verify_32
func Verify_32(x *c.UChar, y *c.UChar) c.Int

//so:extern crypto_verify_64
func Verify_64(x *c.UChar, y *c.UChar) c.Int

//so:extern crypto_xof_shake128
func Xof_shake128(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_shake128_init
func Xof_shake128_init(state *Xof_shake128_state) c.Int

//so:extern crypto_xof_shake128_init_with_domain
func Xof_shake128_init_with_domain(state *Xof_shake128_state, domain c.UChar) c.Int

//so:extern crypto_xof_shake128_update
func Xof_shake128_update(state *Xof_shake128_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_shake128_squeeze
func Xof_shake128_squeeze(state *Xof_shake128_state, out *c.UChar, outlen c.Size) c.Int

//so:extern crypto_xof_shake256
func Xof_shake256(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_shake256_init
func Xof_shake256_init(state *Xof_shake256_state) c.Int

//so:extern crypto_xof_shake256_init_with_domain
func Xof_shake256_init_with_domain(state *Xof_shake256_state, domain c.UChar) c.Int

//so:extern crypto_xof_shake256_update
func Xof_shake256_update(state *Xof_shake256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_shake256_squeeze
func Xof_shake256_squeeze(state *Xof_shake256_state, out *c.UChar, outlen c.Size) c.Int

//so:extern crypto_xof_turboshake128
func Xof_turboshake128(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_turboshake128_init
func Xof_turboshake128_init(state *Xof_turboshake128_state) c.Int

//so:extern crypto_xof_turboshake128_init_with_domain
func Xof_turboshake128_init_with_domain(state *Xof_turboshake128_state, domain c.UChar) c.Int

//so:extern crypto_xof_turboshake128_update
func Xof_turboshake128_update(state *Xof_turboshake128_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_turboshake128_squeeze
func Xof_turboshake128_squeeze(state *Xof_turboshake128_state, out *c.UChar, outlen c.Size) c.Int

//so:extern crypto_xof_turboshake256
func Xof_turboshake256(out *c.UChar, outlen c.Size, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_turboshake256_init
func Xof_turboshake256_init(state *Xof_turboshake256_state) c.Int

//so:extern crypto_xof_turboshake256_init_with_domain
func Xof_turboshake256_init_with_domain(state *Xof_turboshake256_state, domain c.UChar) c.Int

//so:extern crypto_xof_turboshake256_update
func Xof_turboshake256_update(state *Xof_turboshake256_state, in *c.UChar, inlen c.ULongLong) c.Int

//so:extern crypto_xof_turboshake256_squeeze
func Xof_turboshake256_squeeze(state *Xof_turboshake256_state, out *c.UChar, outlen c.Size) c.Int

//so:extern randombytes_buf
func Randombytes_buf(buf any, size c.Size)

//so:extern randombytes_buf_deterministic
func Randombytes_buf_deterministic(buf any, size c.Size, seed *c.UChar)

//so:extern randombytes_random
func Randombytes_random() uint32

//so:extern randombytes_uniform
func Randombytes_uniform(upper_bound uint32) uint32

//so:extern randombytes_stir
func Randombytes_stir()

//so:extern randombytes_close
func Randombytes_close() c.Int

//so:extern randombytes_set_implementation
func Randombytes_set_implementation(impl *Randombytes_implementation) c.Int

//so:extern randombytes_implementation_name
func Randombytes_implementation_name() *c.ConstChar

//so:extern randombytes
func Randombytes(buf *c.UChar, buf_len c.ULongLong)

//so:extern sodium_runtime_has_neon
func Runtime_has_neon() c.Int

//so:extern sodium_runtime_has_armcrypto
func Runtime_has_armcrypto() c.Int

//so:extern sodium_runtime_has_sse2
func Runtime_has_sse2() c.Int

//so:extern sodium_runtime_has_sse3
func Runtime_has_sse3() c.Int

//so:extern sodium_runtime_has_ssse3
func Runtime_has_ssse3() c.Int

//so:extern sodium_runtime_has_sse41
func Runtime_has_sse41() c.Int

//so:extern sodium_runtime_has_avx
func Runtime_has_avx() c.Int

//so:extern sodium_runtime_has_avx2
func Runtime_has_avx2() c.Int

//so:extern sodium_runtime_has_avx512f
func Runtime_has_avx512f() c.Int

//so:extern sodium_runtime_has_pclmul
func Runtime_has_pclmul() c.Int

//so:extern sodium_runtime_has_aesni
func Runtime_has_aesni() c.Int

//so:extern sodium_runtime_has_rdrand
func Runtime_has_rdrand() c.Int

//so:extern sodium_memzero
func Memzero(pnt any, len c.Size)

//so:extern sodium_stackzero
func Stackzero(len c.Size)

//so:extern sodium_memcmp
func Memcmp(b1_ any, b2_ any, len c.Size) c.Int

//so:extern sodium_compare
func Compare(b1_ *c.UChar, b2_ *c.UChar, len c.Size) c.Int

//so:extern sodium_is_zero
func Is_zero(n *c.UChar, nlen c.Size) c.Int

//so:extern sodium_increment
func Increment(n *c.UChar, nlen c.Size)

//so:extern sodium_add
func Add(a *c.UChar, b *c.UChar, len c.Size)

//so:extern sodium_sub
func Sub(a *c.UChar, b *c.UChar, len c.Size)

//so:extern sodium_bin2hex
func Bin2hex(hex *c.Char, hex_maxlen c.Size, bin *c.UChar, bin_len c.Size) *c.Char

//so:extern sodium_hex2bin
func Hex2bin(bin *c.UChar, bin_maxlen c.Size, hex string, hex_len c.Size, ignore string, bin_len *c.Size, hex_end **c.ConstChar) c.Int

//so:extern sodium_base64_encoded_len
func Base64_encoded_len(bin_len c.Size, variant c.Int) c.Size

//so:extern sodium_bin2base64
func Bin2base64(b64 *c.Char, b64_maxlen c.Size, bin *c.UChar, bin_len c.Size, variant c.Int) *c.Char

//so:extern sodium_base642bin
func Base642bin(bin *c.UChar, bin_maxlen c.Size, b64 string, b64_len c.Size, ignore string, bin_len *c.Size, b64_end **c.ConstChar, variant c.Int) c.Int

//so:extern sodium_ip2bin
func Ip2bin(bin *c.UChar, ip string, ip_len_ c.Size) c.Int

//so:extern sodium_bin2ip
func Bin2ip(ip *c.Char, ip_maxlen c.Size, bin *c.UChar) *c.Char

//so:extern sodium_mlock
func Mlock(addr any, len c.Size) c.Int

//so:extern sodium_munlock
func Munlock(addr any, len c.Size) c.Int

//so:extern sodium_malloc
func Malloc(size c.Size) any

//so:extern sodium_allocarray
func Allocarray(count c.Size, size c.Size) any

//so:extern sodium_free
func Free(ptr any)

//so:extern sodium_mprotect_noaccess
func Mprotect_noaccess(ptr any) c.Int

//so:extern sodium_mprotect_readonly
func Mprotect_readonly(ptr any) c.Int

//so:extern sodium_mprotect_readwrite
func Mprotect_readwrite(ptr any) c.Int

//so:extern sodium_pad
func Pad(padded_buflen_p *c.Size, buf *c.UChar, unpadded_buflen c.Size, blocksize c.Size, max_buflen c.Size) c.Int

//so:extern sodium_unpad
func Unpad(unpadded_buflen_p *c.Size, buf *c.UChar, padded_buflen c.Size, blocksize c.Size) c.Int

//so:extern crypto_stream_xchacha20_messagebytes_max
func Stream_xchacha20_messagebytes_max() c.Size

//so:extern crypto_stream_xchacha20
func Stream_xchacha20(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_xchacha20_xor
func Stream_xchacha20_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_xchacha20_xor_ic
func Stream_xchacha20_xor_ic(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, ic uint64, k *c.UChar) c.Int

//so:extern crypto_stream_xchacha20_keygen
func Stream_xchacha20_keygen(k *c.UChar)

//so:extern crypto_box_curve25519xchacha20poly1305_messagebytes_max
func Box_curve25519xchacha20poly1305_messagebytes_max() c.Size

//so:extern crypto_box_curve25519xchacha20poly1305_seed_keypair
func Box_curve25519xchacha20poly1305_seed_keypair(pk *c.UChar, sk *c.UChar, seed *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_keypair
func Box_curve25519xchacha20poly1305_keypair(pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_easy
func Box_curve25519xchacha20poly1305_easy(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_open_easy
func Box_curve25519xchacha20poly1305_open_easy(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_detached
func Box_curve25519xchacha20poly1305_detached(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_open_detached
func Box_curve25519xchacha20poly1305_open_detached(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_beforenm
func Box_curve25519xchacha20poly1305_beforenm(k *c.UChar, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_easy_afternm
func Box_curve25519xchacha20poly1305_easy_afternm(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_open_easy_afternm
func Box_curve25519xchacha20poly1305_open_easy_afternm(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_detached_afternm
func Box_curve25519xchacha20poly1305_detached_afternm(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_open_detached_afternm
func Box_curve25519xchacha20poly1305_open_detached_afternm(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_seal
func Box_curve25519xchacha20poly1305_seal(c *c.UChar, m *c.UChar, mlen c.ULongLong, pk *c.UChar) c.Int

//so:extern crypto_box_curve25519xchacha20poly1305_seal_open
func Box_curve25519xchacha20poly1305_seal_open(m *c.UChar, c *c.UChar, clen c.ULongLong, pk *c.UChar, sk *c.UChar) c.Int

//so:extern crypto_core_ed25519_is_valid_point
func Core_ed25519_is_valid_point(p *c.UChar) c.Int

//so:extern crypto_core_ed25519_add
func Core_ed25519_add(r *c.UChar, p *c.UChar, q *c.UChar) c.Int

//so:extern crypto_core_ed25519_sub
func Core_ed25519_sub(r *c.UChar, p *c.UChar, q *c.UChar) c.Int

//so:extern crypto_core_ed25519_from_uniform
func Core_ed25519_from_uniform(p *c.UChar, r *c.UChar) c.Int

//so:extern crypto_core_ed25519_from_hash
func Core_ed25519_from_hash(p *c.UChar, h *c.UChar) c.Int

//so:extern crypto_core_ed25519_random
func Core_ed25519_random(p *c.UChar)

//so:extern crypto_core_ed25519_scalar_random
func Core_ed25519_scalar_random(r *c.UChar)

//so:extern crypto_core_ed25519_scalar_invert
func Core_ed25519_scalar_invert(recip *c.UChar, s *c.UChar) c.Int

//so:extern crypto_core_ed25519_scalar_negate
func Core_ed25519_scalar_negate(neg *c.UChar, s *c.UChar)

//so:extern crypto_core_ed25519_scalar_complement
func Core_ed25519_scalar_complement(comp *c.UChar, s *c.UChar)

//so:extern crypto_core_ed25519_scalar_add
func Core_ed25519_scalar_add(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ed25519_scalar_sub
func Core_ed25519_scalar_sub(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ed25519_scalar_mul
func Core_ed25519_scalar_mul(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ed25519_scalar_reduce
func Core_ed25519_scalar_reduce(r *c.UChar, s *c.UChar)

//so:extern crypto_core_ristretto255_is_valid_point
func Core_ristretto255_is_valid_point(p *c.UChar) c.Int

//so:extern crypto_core_ristretto255_add
func Core_ristretto255_add(r *c.UChar, p *c.UChar, q *c.UChar) c.Int

//so:extern crypto_core_ristretto255_sub
func Core_ristretto255_sub(r *c.UChar, p *c.UChar, q *c.UChar) c.Int

//so:extern crypto_core_ristretto255_from_hash
func Core_ristretto255_from_hash(p *c.UChar, r *c.UChar) c.Int

//so:extern crypto_core_ristretto255_random
func Core_ristretto255_random(p *c.UChar)

//so:extern crypto_core_ristretto255_scalar_random
func Core_ristretto255_scalar_random(r *c.UChar)

//so:extern crypto_core_ristretto255_scalar_invert
func Core_ristretto255_scalar_invert(recip *c.UChar, s *c.UChar) c.Int

//so:extern crypto_core_ristretto255_scalar_negate
func Core_ristretto255_scalar_negate(neg *c.UChar, s *c.UChar)

//so:extern crypto_core_ristretto255_scalar_complement
func Core_ristretto255_scalar_complement(comp *c.UChar, s *c.UChar)

//so:extern crypto_core_ristretto255_scalar_add
func Core_ristretto255_scalar_add(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ristretto255_scalar_sub
func Core_ristretto255_scalar_sub(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ristretto255_scalar_mul
func Core_ristretto255_scalar_mul(z *c.UChar, x *c.UChar, y *c.UChar)

//so:extern crypto_core_ristretto255_scalar_reduce
func Core_ristretto255_scalar_reduce(r *c.UChar, s *c.UChar)

//so:extern crypto_pwhash_scryptsalsa208sha256_bytes_max
func Pwhash_scryptsalsa208sha256_bytes_max() c.Size

//so:extern crypto_pwhash_scryptsalsa208sha256_passwd_max
func Pwhash_scryptsalsa208sha256_passwd_max() c.Size

//so:extern crypto_pwhash_scryptsalsa208sha256_memlimit_max
func Pwhash_scryptsalsa208sha256_memlimit_max() c.Size

//so:extern crypto_pwhash_scryptsalsa208sha256
func Pwhash_scryptsalsa208sha256(out *c.UChar, outlen c.ULongLong, passwd string, passwdlen c.ULongLong, salt *c.UChar, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_scryptsalsa208sha256_str
func Pwhash_scryptsalsa208sha256_str(out *c.Char, passwd string, passwdlen c.ULongLong, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_pwhash_scryptsalsa208sha256_str_verify
func Pwhash_scryptsalsa208sha256_str_verify(str string, passwd string, passwdlen c.ULongLong) c.Int

//so:extern crypto_pwhash_scryptsalsa208sha256_ll
func Pwhash_scryptsalsa208sha256_ll(passwd *uint8, passwdlen c.Size, salt *uint8, saltlen c.Size, N uint64, r uint32, p uint32, buf *uint8, buflen c.Size) c.Int

//so:extern crypto_pwhash_scryptsalsa208sha256_str_needs_rehash
func Pwhash_scryptsalsa208sha256_str_needs_rehash(str string, opslimit c.ULongLong, memlimit c.Size) c.Int

//so:extern crypto_scalarmult_ed25519
func Scalarmult_ed25519(q *c.UChar, n *c.UChar, p *c.UChar) c.Int

//so:extern crypto_scalarmult_ed25519_noclamp
func Scalarmult_ed25519_noclamp(q *c.UChar, n *c.UChar, p *c.UChar) c.Int

//so:extern crypto_scalarmult_ed25519_base
func Scalarmult_ed25519_base(q *c.UChar, n *c.UChar) c.Int

//so:extern crypto_scalarmult_ed25519_base_noclamp
func Scalarmult_ed25519_base_noclamp(q *c.UChar, n *c.UChar) c.Int

//so:extern crypto_scalarmult_ristretto255
func Scalarmult_ristretto255(q *c.UChar, n *c.UChar, p *c.UChar) c.Int

//so:extern crypto_scalarmult_ristretto255_base
func Scalarmult_ristretto255_base(q *c.UChar, n *c.UChar) c.Int

//so:extern crypto_secretbox_xchacha20poly1305_messagebytes_max
func Secretbox_xchacha20poly1305_messagebytes_max() c.Size

//so:extern crypto_secretbox_xchacha20poly1305_easy
func Secretbox_xchacha20poly1305_easy(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_xchacha20poly1305_open_easy
func Secretbox_xchacha20poly1305_open_easy(m *c.UChar, c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_xchacha20poly1305_detached
func Secretbox_xchacha20poly1305_detached(c *c.UChar, mac *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_secretbox_xchacha20poly1305_open_detached
func Secretbox_xchacha20poly1305_open_detached(m *c.UChar, c *c.UChar, mac *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa2012_messagebytes_max
func Stream_salsa2012_messagebytes_max() c.Size

//so:extern crypto_stream_salsa2012
func Stream_salsa2012(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa2012_xor
func Stream_salsa2012_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa2012_keygen
func Stream_salsa2012_keygen(k *c.UChar)

//so:extern crypto_stream_salsa208_messagebytes_max
func Stream_salsa208_messagebytes_max() c.Size

//so:extern crypto_stream_salsa208
func Stream_salsa208(c *c.UChar, clen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa208_xor
func Stream_salsa208_xor(c *c.UChar, m *c.UChar, mlen c.ULongLong, n *c.UChar, k *c.UChar) c.Int

//so:extern crypto_stream_salsa208_keygen
func Stream_salsa208_keygen(k *c.UChar)
